### ISSUE TITLE
Missing file NUT_DATA.txt

### ISSUE THREAD

**Issue by jrissler** [masilver99/SR28-PSQL#3]
Another missing file, is this intentional?

Thanks

**Comment by masilver99** [comment]
Not intentional.  It's a large file and GitHub wouldn't accept it and I didn't realize that when batch uploading.  I 7zipped it and uploaded it.

**Comment by jrissler** [comment]
Thanks for updates - I ended up getting it to commit, although atom wouldn't open it due to size :) I just copied from command line into repo - and it committed here in my fork: https://github.com/jrissler/SR28-PSQL
